### ISSUE TITLE
Discord.js ClientDataManager TypeError

### ISSUE THREAD

**Issue by IakovTaranenko** [IakovTaranenko/discord-nitro-code-scanner#2]
Error code

```
C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\client\ClientDataManager.js:81
        guild.channels.set(channel.id, channel);
                                   ^

TypeError: Cannot read property 'id' of undefined
    at ClientDataManager.newChannel (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\client\ClientDataManager.js:81:36)
    at Guild.setup (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\structures\Guild.js:307:68)
    at new Guild (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\structures\Guild.js:74:12)
    at ClientDataManager.newGuild (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\client\ClientDataManager.js:26:19)
    at ReadyHandler.handle (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\client\websocket\packets\handlers\Ready.js:20:91)
    at WebSocketPacketManager.handle (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\client\websocket\packets\WebSocketPacketManager.js:108:65)
    at WebSocketConnection.onPacket (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:336:35)
    at WebSocketConnection.onMessage (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\discord.js\src\client\websocket\WebSocketConnection.js:299:17)
    at WebSocket.onMessage (C:\Users\Xeus\Documents\GitHub\discord-nitro-code-scanner\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:321:20)
```

**Comment by IakovTaranenko** [comment]
Fixed in commit 3eb6c7ecf137e0bf6d0e5b7f25da13917fca98e0
